### PR TITLE
fix rpc-calls autocomplete bug, remove pre-chosen method

### LINKED ISSUE #168: Input for method name on RPC calls should be empty by default
Right now it might cause confusion for first time users:
1. It doesnt look like an input so you don't know the content can be erased.
2. Because there is something in input the dropdown will only show a single option.

Proposed solution:
make a placeholder instead of the actual content.

### PR DESCRIPTION
**Pull request by goldylucks**
the bug was caused by re-rendering the component which resets the autocomplete selection

fixes #168 #169

### CODE REVIEW

File: client/components/RpcCalls/RpcCalls.js [hunk 1]
```diff
@@ -38,6 +39,12 @@ export default class RpcCalls extends Component {
     }
   }
 
+  shouldComponentUpdate (nextProps, nextState) {
```
Comment (tomusdrw) [inline client/components/RpcCalls/RpcCalls.js]: Maybe it would be safer to create a separate component from AutoComplete? Like RPC method AutoComplete - it seems to be only using `rpcMethodNames`.

Comment (goldylucks) [inline client/components/RpcCalls/RpcCalls.js]: I think it can b done in another PR

in anyway shouldCoponentUpdte isbest practice for performance

Comment (tomusdrw) [inline client/components/RpcCalls/RpcCalls.js]: Yeah, but to right now anything that happens in this component needs to be included in `shouldComponentUpdate` - and we care only about `AutoComplete` component.

So my reasoning that the smaller the component is the easier is to keep `shouldComponentUpdate` without bugs.

File: client/provider/rpc-provider.js [hunk 2]
```diff
@@ -51,7 +51,7 @@ export default class RpcProvider {
       }
 
       try {
-        return `${formatter(param)}`;
+        return formatter(param);
```
Comment (goldylucks) [inline client/provider/rpc-provider.js]: @tomusdrw do u remember why we cohersed into string in the first place?

**Comment by goldylucks** [comment]
@tomusdrw plz review last 3 commits

File: client/provider/rpc-provider.js (hunk 2 above)
Comment (tomusdrw) [inline client/provider/rpc-provider.js]: I guess we were expecting state data to be ready to display, but not really sure.
