### PR TITLE
fix call params display

### LINKED ISSUE #157: When firing the call with object parameter the history doesnt show the parameters correctly.
screenshot from 2016-05-23 12 05 25

### PR DESCRIPTION
**Pull request by goldylucks**
fixes #157

### CODE REVIEW

**Comment by tomusdrw** [comment]
Does it look good with large objects? Like the one in `sendTransaction`?

**Comment by goldylucks** [comment]
@tomusdrw I've added a commit u wanna go over it?

File: client/components/Call/Call.js [hunk 1]
```diff
@@ -30,6 +30,21 @@ export default class Call extends Component {
     this.props.setActiveCall(this.props.call, this.element);
   }
 
+  formatParams (params) {
```
Comment (jacogr) [inline client/components/Call/Call.js]: This may have made more sense in `util/`, we do some formatting in there already. (Although this is not used anywhere as of yet, but it is rather generic)

Comment (goldylucks) [inline client/components/Call/Call.js]: yea I thought about generalizing it when the time comes

**Comment by tomusdrw** [comment]
lgtm
